# Generated by Django 2.0.7 on 2018-08-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vocab_freq_central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_east',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_north',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_south',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vocab_freq_west',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=50)),
                ('frequency', models.BigIntegerField()),
            ],
        ),
    ]
